//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasApi_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniEncuestaPopupRespuestaAlumno
    {
        public int IdEncuesta { get; set; }
        public int IdPregunta { get; set; }
        public int Legajo { get; set; }
        public Nullable<int> RespuestaNumerica { get; set; }
        public string RespuestaTexto { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
