//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasApi_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class uniEncuestaRegistroAlumnos
    {
        public int IdEncuestaRegistroAlumno { get; set; }
        public string AlumnoDNI { get; set; }
        public string LegajoProvisorio { get; set; }
        public string Legajo { get; set; } //Definitivo
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Carrera { get; set; }
        public string Modalidad { get; set; }
    }
}
