//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasApi_DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class UniEncuesta_Entities : DbContext
    {
        public UniEncuesta_Entities()
            : base("name=UniEncuesta_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uniEncuestaPopup> uniEncuestaPopup { get; set; }
        public virtual DbSet<uniEncuestaPopupPregunta> uniEncuestaPopupPregunta { get; set; }
        public virtual DbSet<uniEncuestaPreguntaTipo> uniEncuestaPreguntaTipo { get; set; }
        public virtual DbSet<vUniAlumnosUsername> vUniAlumnosUsername { get; set; }
        public virtual DbSet<uniEncuestaPopupRespuestaAlumno> uniEncuestaPopupRespuestaAlumno { get; set; }
        public virtual DbSet<uniEncuestaRegistroAlumnos> uniEncuestaRegistroAlumnos { get; set; }
    
        public virtual ObjectResult<sp_get_uni_encuesta_registro_alumnos_Result> sp_get_uni_encuesta_registro_alumnos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_uni_encuesta_registro_alumnos_Result>("sp_get_uni_encuesta_registro_alumnos");
        }
    }
}
